DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS trivia;

CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE trivia(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL,
  link VARCHAR(255) NOT NULL
);
