# Use a base image with NGINX installed
FROM nginx

# Copy the website files to the appropriate directory in the container
COPY ./html /usr/share/nginx/html

# Expose port 80 for incoming traffic
EXPOSE 80

# Start NGINX when the container runs
CMD ["nginx", "-g", "daemon off;"]

