name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, be sure to be as informative as possible when submitting your issue!"
        pr-message: "Hey, looks like it's your first pull-request. If you have a Dockerfile, please make sure to test it before making the PR :smile:"
