name: Pull Request Auto Labeller

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_labeller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto Labelling
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = "Docker";
            const changedFiles = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const hasDockerfile = changedFiles.data.some(file => file.filename.toLowerCase().endsWith("dockerfile"));

            if (hasDockerfile) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [labelName]
              });
            }
