name: Pull Request Labeler

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Request Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration:
            Docker:
              - Dockerfile
